In [1]:
import numpy as np

In [2]:
# 1. create a null vector / 1D array of size 10 and update fifth index to 11.

In [3]:
array_ku = np.zeros(10)
array_ku

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
array_ku[5]='11'
array_ku

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

In [5]:
# 2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [6]:
x = np.array([[1,2,3],
             [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
y = x.reshape(3,2)
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
x.ndim

2

In [9]:
# 3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [10]:
d_array = np.ones((5,5))
d_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
d_array[1:-1, 2:-1]=0
d_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 1.],
       [1., 1., 0., 0., 1.],
       [1., 1., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# 4. Take a look at the following matrix. Access the [2, 1, 1]

In [13]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])
z

array([[[ 0,  1,  3],
        [ 5,  7,  9],
        [ 6,  8, 10]],

       [[ 0,  2,  4],
        [ 6,  8, 10],
        [ 0,  1,  3]],

       [[ 1,  1,  2],
        [ 5,  2,  9],
        [ 1,  3,  3]]])

In [14]:
s = z[2,1,1]
s

2

ASSIGNMENT
1. Create a 4x4 matrix with values ranging from 0 to 3.
   (The following image is just as an example. It doesn't represent the real image of arrays in the question)

In [15]:
# cara pertama

matrix_4x4_1 = np.zeros((4,4))
matrix_4x4_1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
matrix_4x4_1 += np.arange(4)
matrix_4x4_1

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [17]:
# cara kedua 

def matrix():
    d = []
    matrix_4x4 = np.arange(0,4)
    for i in matrix_4x4:
        d.append(i)
    return d

for i in range(4):
    if i <= 4:
        r = matrix()
    print(r)


[0, 1, 2, 3]
[0, 1, 2, 3]
[0, 1, 2, 3]
[0, 1, 2, 3]


2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.

In [18]:
a = np.array([[1, 2, 8, 11],
             [5, 8, 10, 12],
             [8, 2, 1, 13],
             [3, 9, 1, 14]])
a

array([[ 1,  2,  8, 11],
       [ 5,  8, 10, 12],
       [ 8,  2,  1, 13],
       [ 3,  9,  1, 14]])

In [21]:
np.hsplit(a, [2,6])

[array([[1, 2],
        [5, 8],
        [8, 2],
        [3, 9]]),
 array([[ 8, 11],
        [10, 12],
        [ 1, 13],
        [ 1, 14]]),
 array([], shape=(4, 0), dtype=int32)]